### ISSUE TITLE
Postman: failed to import, format not recognized

### ISSUE THREAD

**Issue by JenniNord** [th222fa/1DV450_API#1]
Hej!
Har fått som uppgift att reviewa ditt API den här veckan och postman filen går inte att importera för mig, varken i Postman - REST Client (Packaged app) eller i Postman - REST Client. Har googlat runt lite för lösningar men verkar som att det är ett känt problem. Ska fortsätta leta efter en lösning men i värsta fall så får jag skriva en ny collection.

**Comment by JenniNord** [comment]
Tålamod löste problemet! Gick via settings > data > import data istället för Collections > Import som tydligen bara är i beta stadiet ;)

**Comment by Guepen** [comment]
Hej! Skönt att det löste sig och tack för tipset!

/Tobias
Den 2 mar 2015 23:30 skrev "Jennifer Nord" notifications@github.com:
