### ISSUE TITLE
Problem med postmanfil

### ISSUE THREAD

**Issue by 1dv450** [th222fa/1DV450_API#11]
Är det bara jag som får problem med att köra in din postman-fil? Verkar vara beskrivet här: https://github.com/a85/POSTMan-Chrome-Extension/issues/556 , då ditt format ser lite konstig ut. Kanske kan kolla upp det att du kan importera din collection?

Jag får kolla upp API:et utan dessa tester...

**Comment by Guepen** [comment]
När jag gör detta via settings > data > import data så fungerar det.

**Comment by 1dv450** [comment]
Sweet. Körde en äldre version där den möjligheten inte fanns.
