### ISSUE TITLE
API nyckel

### ISSUE THREAD

**Issue by JenniNord** [th222fa/1DV450_API#2]
För att få en bra helhetskänsla över applikationen så är det verkligen jättebra att du har kopplat ihop registreringen med api'et men det hade varit skönt med en api-nyckel som låg som ett seed som skapades automatiskt. På så sätt så hade du kunnat använda den nyckeln i anropen i postman filen så hade jag inte behövt gå in och ändra i varje anrop. Men så klart så är det bara en bekvämlighets grej för mig som testare :)

**Comment by 1dv450** [comment]
:+1:
