### ISSUE TITLE
Hämta en creators caféer

### ISSUE THREAD

**Issue by JenniNord** [th222fa/1DV450_API#7]
"Hämta en creators caféer" anropet ger mig ett NoMethodError.

"undefined method 'coffeehouses' for nil:NilClass"

**Comment by JenniNord** [comment]
Även "Hämta caféer som matcher sökquery och tillhör en creator" ger detta fel.

**Comment by Guepen** [comment]
Detta beror nog på att det inte finns någon creator med det id:t som du har i URL:en. Fungerar det att hämta alla creators? I så fall kan du se vilka creators-id det finns. Har inte hunnit lägga till felhantering på allt ännu

**Comment by JenniNord** [comment]
Det har du rätt i! Ändrade till creator med id 1 och då så fungerade det bättre.
